### ISSUE TITLE
布局无法设置大小

### ISSUE THREAD

**Issue by chenkexu** [dqh147258/ClipPathLayout#1]
![image](https://user-images.githubusercontent.com/14785825/139034249-13e9834b-48dc-4777-bffd-1e6c24532c76.png)
 布局无法设置大小，总大小占满整个屏幕，怎么修改一下

**Comment by dqh147258** [comment]
你用match_parent不就完了............
ClipPathLayout并不侵入父布局的长宽和布局配置........原本的FrameLayout怎么使用ClipPathFrameLayout的用法也是一样.......
